export const LIST_MOVIES_LOADING = 'LIST_MOVIES_LOADING'
export const LIST_MOVIES_ERROR = 'LIST_MOVIES_ERROR'

export const LIST_MOVIES_SUCCESS = 'LIST_MOVIES_SUCCESS'
export const DETAIL_MOVIES_SUCCESS = 'DETAIL_MOVIES_SUCCESS'